import path from "path"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    proxy: {
      '/auth': 'http://localhost:8088',
      '/api': 'http://localhost:8088',
      '/disputes': 'http://localhost:8088',
      '/push': 'http://localhost:8088',
      '/healthz': 'http://localhost:8088',
      '/elections': 'http://localhost:8088',
      '/results': 'http://localhost:8088',
      '/collation': 'http://localhost:8088',
      '/dashboard': 'http://localhost:8088',
      '/observer': 'http://localhost:8088',
      '/bvas': 'http://localhost:8088',
      '/audit': 'http://localhost:8088',
      '/incidents': 'http://localhost:8088',
      '/kyc': 'http://localhost:8088',
      '/scale': 'http://localhost:8088',
      '/middleware': 'http://localhost:8088',
      '/document-ai': 'http://localhost:8088',
      '/polling-units': 'http://localhost:8088',
      '/ai': 'http://localhost:8088',
      '/biometric': 'http://localhost:8088',
      '/blockchain': 'http://localhost:8088',
      '/voters': 'http://localhost:8088',
      '/workflows': 'http://localhost:8088',
      '/portals': 'http://localhost:8088',
      '/validation': 'http://localhost:8088',
      '/sms': 'http://localhost:8088',
      '/public-api': 'http://localhost:8088',
      '/geo': 'http://localhost:8088',
      '/geofence': 'http://localhost:8088',
      '/export': 'http://localhost:8088',
      '/admin': 'http://localhost:8088',
      '/db': 'http://localhost:8088',
      '/pgpool': 'http://localhost:8088',
      '/ems': 'http://localhost:8088',
      '/command-center': 'http://localhost:8088',
      '/escalation': 'http://localhost:8088',
      '/load-shedding': 'http://localhost:8088',
      '/citizen': 'http://localhost:8088',
      '/media': 'http://localhost:8088',
      '/openapi.json': 'http://localhost:8088',
      '/anomaly': 'http://localhost:8088',
      '/predictive': 'http://localhost:8088',
      '/election': 'http://localhost:8088',
      '/data': 'http://localhost:8088',
      '/offline': 'http://localhost:8088',
      '/ivr': 'http://localhost:8088',
      '/inec': 'http://localhost:8088',
      '/metrics': 'http://localhost:8088',
      '/readiness': 'http://localhost:8088',
      '/parties': 'http://localhost:8088',
      '/ingestion': 'http://localhost:8088',
      '/training': 'http://localhost:8088',
      '/stakeholders': 'http://localhost:8088',
      '/production': 'http://localhost:8088',
      '/ussd': 'http://localhost:8088',
      '/kyb': 'http://localhost:8088',
      '/security': 'http://localhost:8088',
      '/users': 'http://localhost:8088',
      '/presence': 'http://localhost:8088',
      '/reports': 'http://localhost:8088',
      '/voice': 'http://localhost:8088',
      '/public': 'http://localhost:8088',
      '/gotv': { target: 'http://localhost:8103', ws: true },
    },
  },
})

