apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fluvio-binding
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "fluvio-sc:9003"
  - name: topics
    value: "inec.results.submitted,inec.incidents.reported,inec.audit.log"
  - name: consumerGroup
    value: "dapr-consumer"
  - name: publishTopic
    value: "inec.results.submitted"
