apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: audit-binding
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: kafka:29092
    - name: topics
      value: audit-events
    - name: consumerGroup
      value: inec-audit
    - name: authType
      value: none
    - name: publishTopic
      value: audit-events
