-- ============================================================================
-- HAND-WRITTEN migration (security/data-integrity audit fix, not generated by
-- drizzle-kit). Apply with the normal migrator or psql; statements are
-- idempotent where possible.
--
-- 1. Money columns move from float4 (real) to exact numeric(15,2):
--    - fundraising_transactions.amount
--    - budget_items.budgeted_amount / spent_amount
--    - diaspora_contacts.pledged_amount
-- 2. Partial unique index on candidate_profiles.user_id (closes the
--    getOrCreateUserProfile check-then-insert race; NULL user_id rows from the
--    shared Go-owned setup are unaffected).
-- 3. Composite index on campaign_members(profile_id, user_id) for the
--    per-request getMyRoleForProfile membership lookup.
-- ============================================================================
ALTER TABLE "fundraising_transactions" ALTER COLUMN "amount" SET DATA TYPE numeric(15,2) USING "amount"::numeric(15,2);--> statement-breakpoint
ALTER TABLE "budget_items" ALTER COLUMN "budgeted_amount" SET DATA TYPE numeric(15,2) USING "budgeted_amount"::numeric(15,2);--> statement-breakpoint
ALTER TABLE "budget_items" ALTER COLUMN "spent_amount" SET DATA TYPE numeric(15,2) USING "spent_amount"::numeric(15,2);--> statement-breakpoint
ALTER TABLE "diaspora_contacts" ALTER COLUMN "pledged_amount" SET DATA TYPE numeric(15,2) USING COALESCE("pledged_amount", 0)::numeric(15,2);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "candidate_profiles_user_id_unique" ON "candidate_profiles" USING btree ("user_id") WHERE "user_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaign_members_profile_user_idx" ON "campaign_members" USING btree ("profile_id", "user_id");
--> statement-breakpoint
-- 4. Columns the routers already write but the schema previously dropped
--    silently (drizzle ignores unknown keys in .values()):
ALTER TABLE "election_results" ADD COLUMN IF NOT EXISTS "ward" varchar(100);--> statement-breakpoint
ALTER TABLE "social_media_posts" ADD COLUMN IF NOT EXISTS "hashtags" text;
