-- ============================================================================
-- HAND-WRITTEN migration (shared rate-limit store, not generated by
-- drizzle-kit). Apply with the normal migrator or psql; idempotent — safe to
-- re-apply.
--
-- Backs server/_core/rateLimit.ts: the login throttle, the per-user LLM call
-- cap, and the public petition-sign dedup/rate limit were per-process
-- in-memory maps, so limits reset on restart and never held across replicas.
-- Fixed-window counters keyed by (key, window_start) make them durable and
-- shared. Old windows are pruned by the helper (DELETE of expired rows).
-- ============================================================================
CREATE TABLE IF NOT EXISTS "rate_limits" (
	"key" text NOT NULL,
	"window_start" timestamptz NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "rate_limits_pkey" PRIMARY KEY("key","window_start")
);
