policies:
- mode: prevent
  name: inec-waf-policy
  rules:
  - action: block
    name: block-sql-injection
    type: sqli
  - action: block
    name: block-xss
    type: xss
  - action: challenge
    limit: 5
    name: rate-limit-login
    type: rate-limit
    uri: /auth/login
    window: 60
  - action: block
    confidence: high
    name: block-malicious-bots
    type: bot-protection
  - action: block
    allowed_countries:
    - NG
    name: geo-block-non-ng
    type: geo
  - action: Redirect
    name: Enforce HTTPS
    type: https-enforcement
  - action: Block
    log: true
    name: CSRF Protection
    type: csrf
  triggers:
  - log
  - block
