policies:
  - name: inec-waf-policy
    mode: prevent
    triggers:
      - log
      - block
    rules:
      - name: block-sql-injection
        type: sqli
        action: block
      - name: block-xss
        type: xss
        action: block
      - name: rate-limit-login
        type: rate-limit
        uri: "/auth/login"
        limit: 5
        window: 60
        action: challenge
      - name: block-malicious-bots
        type: bot-protection
        action: block
        confidence: high
      - name: geo-block-non-ng
        type: geo
        allowed_countries: ["NG"]
        action: block
