-- Migration 000024: Schema reconciliation
-- Adds columns referenced by live code but missing from table definitions,
-- and relaxes legacy NOT NULL constraints that newer code paths cannot satisfy.
-- Generated by schema audit (INSERT column lists vs CREATE TABLE defs).

-- api_key_metadata
DO $$
BEGIN
    IF to_regclass('api_key_metadata') IS NOT NULL THEN
        ALTER TABLE "api_key_metadata" ADD COLUMN IF NOT EXISTS "environment" TEXT;
    ELSE
        RAISE WARNING 'table api_key_metadata missing; column environment not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('api_key_metadata') IS NOT NULL THEN
        ALTER TABLE "api_key_metadata" ADD COLUMN IF NOT EXISTS "last_used" TIMESTAMP;
    ELSE
        RAISE WARNING 'table api_key_metadata missing; column last_used not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('api_key_metadata') IS NOT NULL THEN
        ALTER TABLE "api_key_metadata" ADD COLUMN IF NOT EXISTS "owner" TEXT;
    ELSE
        RAISE WARNING 'table api_key_metadata missing; column owner not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('api_key_metadata') IS NOT NULL THEN
        ALTER TABLE "api_key_metadata" ADD COLUMN IF NOT EXISTS "permissions" JSONB;
    ELSE
        RAISE WARNING 'table api_key_metadata missing; column permissions not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('api_key_metadata') IS NOT NULL THEN
        ALTER TABLE "api_key_metadata" ADD COLUMN IF NOT EXISTS "rate_limit" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table api_key_metadata missing; column rate_limit not added';
    END IF;
END $$;

-- api_usage
DO $$
BEGIN
    IF to_regclass('api_usage') IS NOT NULL THEN
        ALTER TABLE "api_usage" ADD COLUMN IF NOT EXISTS "key_id" INTEGER;
    ELSE
        RAISE WARNING 'table api_usage missing; column key_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('api_usage') IS NOT NULL THEN
        ALTER TABLE "api_usage" ADD COLUMN IF NOT EXISTS "response_time_ms" INTEGER;
    ELSE
        RAISE WARNING 'table api_usage missing; column response_time_ms not added';
    END IF;
END $$;

-- audit_log
DO $$
BEGIN
    IF to_regclass('audit_log') IS NOT NULL THEN
        ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "performed_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table audit_log missing; column performed_at not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('audit_log') IS NOT NULL THEN
        ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "performed_by" TEXT;
    ELSE
        RAISE WARNING 'table audit_log missing; column performed_by not added';
    END IF;
END $$;

-- biometric_match_log
DO $$
BEGIN
    IF to_regclass('biometric_match_log') IS NOT NULL THEN
        ALTER TABLE "biometric_match_log" ADD COLUMN IF NOT EXISTS "is_match" BOOLEAN;
    ELSE
        RAISE WARNING 'table biometric_match_log missing; column is_match not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_match_log') IS NOT NULL THEN
        ALTER TABLE "biometric_match_log" ADD COLUMN IF NOT EXISTS "template_id_a" TEXT;
    ELSE
        RAISE WARNING 'table biometric_match_log missing; column template_id_a not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_match_log') IS NOT NULL THEN
        ALTER TABLE "biometric_match_log" ADD COLUMN IF NOT EXISTS "template_id_b" TEXT;
    ELSE
        RAISE WARNING 'table biometric_match_log missing; column template_id_b not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_match_log') IS NOT NULL THEN
        ALTER TABLE "biometric_match_log" ADD COLUMN IF NOT EXISTS "threshold" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_match_log missing; column threshold not added';
    END IF;
END $$;

-- biometric_profiles
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column device_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "enrollment_center" TEXT;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column enrollment_center not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "enrollment_status" TEXT;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column enrollment_status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "facial_quality" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column facial_quality not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "fingerprint_quality" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column fingerprint_quality not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "iris_quality" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column iris_quality not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "last_verified" TEXT;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column last_verified not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "operator_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column operator_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "photo_hash" TEXT;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column photo_hash not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "verification_count" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column verification_count not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "vin" TEXT;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column vin not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_profiles') IS NOT NULL THEN
        ALTER TABLE "biometric_profiles" ADD COLUMN IF NOT EXISTS "voter_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_profiles missing; column voter_id not added';
    END IF;
END $$;

-- biometric_quality_scores
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "contrast" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column contrast not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "iso_quality" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column iso_quality not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "minutiae_count" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column minutiae_count not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "nfiq_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column nfiq_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "sharpness" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column sharpness not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "template_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column template_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_quality_scores') IS NOT NULL THEN
        ALTER TABLE "biometric_quality_scores" ADD COLUMN IF NOT EXISTS "uniformity" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_quality_scores missing; column uniformity not added';
    END IF;
END $$;

-- biometric_templates
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "captured_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column captured_at not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column device_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "encrypted_template" TEXT;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column encrypted_template not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column is_active not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "profile_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column profile_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "template_hash" TEXT;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column template_hash not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "template_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column template_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_templates') IS NOT NULL THEN
        ALTER TABLE "biometric_templates" ADD COLUMN IF NOT EXISTS "version" TEXT;
    ELSE
        RAISE WARNING 'table biometric_templates missing; column version not added';
    END IF;
END $$;

-- biometric_verifications
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column latitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "liveness_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column liveness_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column longitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "match_result" BOOLEAN;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column match_result not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "operator_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column operator_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "processing_time_ms" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column processing_time_ms not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "profile_id" INTEGER;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column profile_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "quality_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column quality_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('biometric_verifications') IS NOT NULL THEN
        ALTER TABLE "biometric_verifications" ADD COLUMN IF NOT EXISTS "score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table biometric_verifications missing; column score not added';
    END IF;
END $$;

-- blockchain_audit_trail
DO $$
BEGIN
    IF to_regclass('blockchain_audit_trail') IS NOT NULL THEN
        ALTER TABLE "blockchain_audit_trail" ADD COLUMN IF NOT EXISTS "block_number" INTEGER;
    ELSE
        RAISE WARNING 'table blockchain_audit_trail missing; column block_number not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('blockchain_audit_trail') IS NOT NULL THEN
        ALTER TABLE "blockchain_audit_trail" ADD COLUMN IF NOT EXISTS "channel" TEXT;
    ELSE
        RAISE WARNING 'table blockchain_audit_trail missing; column channel not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('blockchain_audit_trail') IS NOT NULL THEN
        ALTER TABLE "blockchain_audit_trail" ADD COLUMN IF NOT EXISTS "data_hash" TEXT;
    ELSE
        RAISE WARNING 'table blockchain_audit_trail missing; column data_hash not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('blockchain_audit_trail') IS NOT NULL THEN
        ALTER TABLE "blockchain_audit_trail" ADD COLUMN IF NOT EXISTS "verified" BOOLEAN;
    ELSE
        RAISE WARNING 'table blockchain_audit_trail missing; column verified not added';
    END IF;
END $$;

-- bvas_accreditations
DO $$
BEGIN
    IF to_regclass('bvas_accreditations') IS NOT NULL THEN
        ALTER TABLE "bvas_accreditations" ADD COLUMN IF NOT EXISTS "match_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_accreditations missing; column match_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_accreditations') IS NOT NULL THEN
        ALTER TABLE "bvas_accreditations" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table bvas_accreditations missing; column status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_accreditations') IS NOT NULL THEN
        ALTER TABLE "bvas_accreditations" ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMP;
    ELSE
        RAISE WARNING 'table bvas_accreditations missing; column timestamp not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_accreditations') IS NOT NULL THEN
        ALTER TABLE "bvas_accreditations" ADD COLUMN IF NOT EXISTS "voter_vin" TEXT;
    ELSE
        RAISE WARNING 'table bvas_accreditations missing; column voter_vin not added';
    END IF;
END $$;

-- bvas_capture_sessions
DO $$
BEGIN
    IF to_regclass('bvas_capture_sessions') IS NOT NULL THEN
        ALTER TABLE "bvas_capture_sessions" ADD COLUMN IF NOT EXISTS "attempt_number" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_capture_sessions missing; column attempt_number not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_capture_sessions') IS NOT NULL THEN
        ALTER TABLE "bvas_capture_sessions" ADD COLUMN IF NOT EXISTS "capture_type" TEXT;
    ELSE
        RAISE WARNING 'table bvas_capture_sessions missing; column capture_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_capture_sessions') IS NOT NULL THEN
        ALTER TABLE "bvas_capture_sessions" ADD COLUMN IF NOT EXISTS "duration_ms" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_capture_sessions missing; column duration_ms not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_capture_sessions') IS NOT NULL THEN
        ALTER TABLE "bvas_capture_sessions" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_capture_sessions missing; column latitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_capture_sessions') IS NOT NULL THEN
        ALTER TABLE "bvas_capture_sessions" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_capture_sessions missing; column longitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_capture_sessions') IS NOT NULL THEN
        ALTER TABLE "bvas_capture_sessions" ADD COLUMN IF NOT EXISTS "success" BOOLEAN;
    ELSE
        RAISE WARNING 'table bvas_capture_sessions missing; column success not added';
    END IF;
END $$;

-- bvas_device_capabilities
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "battery_capacity_mah" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column battery_capacity_mah not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "connectivity" TEXT;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column connectivity not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "facial_camera" TEXT;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column facial_camera not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "gps_module" TEXT;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column gps_module not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "iris_scanner" TEXT;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column iris_scanner not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "nfc_reader" TEXT;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column nfc_reader not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "os_version" TEXT;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column os_version not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "ram_mb" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column ram_mb not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "screen_size_inch" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column screen_size_inch not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "sim_slots" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column sim_slots not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_device_capabilities') IS NOT NULL THEN
        ALTER TABLE "bvas_device_capabilities" ADD COLUMN IF NOT EXISTS "storage_gb" INTEGER;
    ELSE
        RAISE WARNING 'table bvas_device_capabilities missing; column storage_gb not added';
    END IF;
END $$;

-- bvas_heartbeats
DO $$
BEGIN
    IF to_regclass('bvas_heartbeats') IS NOT NULL THEN
        ALTER TABLE "bvas_heartbeats" ADD COLUMN IF NOT EXISTS "gps_lat" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_heartbeats missing; column gps_lat not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_heartbeats') IS NOT NULL THEN
        ALTER TABLE "bvas_heartbeats" ADD COLUMN IF NOT EXISTS "gps_lng" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_heartbeats missing; column gps_lng not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_heartbeats') IS NOT NULL THEN
        ALTER TABLE "bvas_heartbeats" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table bvas_heartbeats missing; column status not added';
    END IF;
END $$;

-- bvas_location_logs
DO $$
BEGIN
    IF to_regclass('bvas_location_logs') IS NOT NULL THEN
        ALTER TABLE "bvas_location_logs" ADD COLUMN IF NOT EXISTS "accuracy" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_location_logs missing; column accuracy not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_location_logs') IS NOT NULL THEN
        ALTER TABLE "bvas_location_logs" ADD COLUMN IF NOT EXISTS "altitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table bvas_location_logs missing; column altitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_location_logs') IS NOT NULL THEN
        ALTER TABLE "bvas_location_logs" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
    ELSE
        RAISE WARNING 'table bvas_location_logs missing; column device_id not added';
    END IF;
END $$;

-- bvas_sync_queue
DO $$
BEGIN
    IF to_regclass('bvas_sync_queue') IS NOT NULL THEN
        ALTER TABLE "bvas_sync_queue" ADD COLUMN IF NOT EXISTS "data_type" TEXT;
    ELSE
        RAISE WARNING 'table bvas_sync_queue missing; column data_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('bvas_sync_queue') IS NOT NULL THEN
        ALTER TABLE "bvas_sync_queue" ADD COLUMN IF NOT EXISTS "payload_size" TEXT;
    ELSE
        RAISE WARNING 'table bvas_sync_queue missing; column payload_size not added';
    END IF;
END $$;

-- cancelable_transforms
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cancelable_transforms' AND column_name='seed') THEN
        ALTER TABLE "cancelable_transforms" ALTER COLUMN "seed" DROP NOT NULL;
    END IF;
END $$;

-- collation_party_scores
DO $$
BEGIN
    IF to_regclass('collation_party_scores') IS NOT NULL THEN
        ALTER TABLE "collation_party_scores" ADD COLUMN IF NOT EXISTS "collation_id" INTEGER;
    ELSE
        RAISE WARNING 'table collation_party_scores missing; column collation_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='collation_party_scores' AND column_name='collation_result_id') THEN
        ALTER TABLE "collation_party_scores" ALTER COLUMN "collation_result_id" DROP NOT NULL;
    END IF;
END $$;

-- collation_results
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "code" TEXT;
    ELSE
        RAISE WARNING 'table collation_results missing; column code not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "collated_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table collation_results missing; column collated_at not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "collation_officer_id" INTEGER;
    ELSE
        RAISE WARNING 'table collation_results missing; column collation_officer_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "total_accredited" INTEGER;
    ELSE
        RAISE WARNING 'table collation_results missing; column total_accredited not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "total_registered" INTEGER;
    ELSE
        RAISE WARNING 'table collation_results missing; column total_registered not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "total_rejected" INTEGER;
    ELSE
        RAISE WARNING 'table collation_results missing; column total_rejected not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "total_valid" INTEGER;
    ELSE
        RAISE WARNING 'table collation_results missing; column total_valid not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('collation_results') IS NOT NULL THEN
        ALTER TABLE "collation_results" ADD COLUMN IF NOT EXISTS "total_votes" INTEGER;
    ELSE
        RAISE WARNING 'table collation_results missing; column total_votes not added';
    END IF;
END $$;

-- crowd_density
DO $$
BEGIN
    ALTER TABLE "crowd_density" ADD COLUMN IF NOT EXISTS "geom" GEOGRAPHY(POINT,4326);
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'skipping crowd_density.geom: %', SQLERRM;
END $$;

-- data_classification
DO $$
BEGIN
    IF to_regclass('data_classification') IS NOT NULL THEN
        ALTER TABLE "data_classification" ADD COLUMN IF NOT EXISTS "field_name" TEXT;
    ELSE
        RAISE WARNING 'table data_classification missing; column field_name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('data_classification') IS NOT NULL THEN
        ALTER TABLE "data_classification" ADD COLUMN IF NOT EXISTS "is_encrypted" BOOLEAN;
    ELSE
        RAISE WARNING 'table data_classification missing; column is_encrypted not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='data_classification' AND column_name='column_name') THEN
        ALTER TABLE "data_classification" ALTER COLUMN "column_name" DROP NOT NULL;
    END IF;
END $$;

-- data_encryption_keys
DO $$
BEGIN
    IF to_regclass('data_encryption_keys') IS NOT NULL THEN
        ALTER TABLE "data_encryption_keys" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;
    ELSE
        RAISE WARNING 'table data_encryption_keys missing; column is_active not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('data_encryption_keys') IS NOT NULL THEN
        ALTER TABLE "data_encryption_keys" ADD COLUMN IF NOT EXISTS "rotation_interval_days" INTEGER;
    ELSE
        RAISE WARNING 'table data_encryption_keys missing; column rotation_interval_days not added';
    END IF;
END $$;

-- dedup_candidates
DO $$
BEGIN
    IF to_regclass('dedup_candidates') IS NOT NULL THEN
        ALTER TABLE "dedup_candidates" ADD COLUMN IF NOT EXISTS "match_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table dedup_candidates missing; column match_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_candidates') IS NOT NULL THEN
        ALTER TABLE "dedup_candidates" ADD COLUMN IF NOT EXISTS "modality" TEXT;
    ELSE
        RAISE WARNING 'table dedup_candidates missing; column modality not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_candidates') IS NOT NULL THEN
        ALTER TABLE "dedup_candidates" ADD COLUMN IF NOT EXISTS "profile_id_a" TEXT;
    ELSE
        RAISE WARNING 'table dedup_candidates missing; column profile_id_a not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_candidates') IS NOT NULL THEN
        ALTER TABLE "dedup_candidates" ADD COLUMN IF NOT EXISTS "profile_id_b" TEXT;
    ELSE
        RAISE WARNING 'table dedup_candidates missing; column profile_id_b not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_candidates') IS NOT NULL THEN
        ALTER TABLE "dedup_candidates" ADD COLUMN IF NOT EXISTS "review_notes" TEXT;
    ELSE
        RAISE WARNING 'table dedup_candidates missing; column review_notes not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_candidates') IS NOT NULL THEN
        ALTER TABLE "dedup_candidates" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table dedup_candidates missing; column status not added';
    END IF;
END $$;

-- dedup_jobs
DO $$
BEGIN
    IF to_regclass('dedup_jobs') IS NOT NULL THEN
        ALTER TABLE "dedup_jobs" ADD COLUMN IF NOT EXISTS "algorithm" TEXT;
    ELSE
        RAISE WARNING 'table dedup_jobs missing; column algorithm not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_jobs') IS NOT NULL THEN
        ALTER TABLE "dedup_jobs" ADD COLUMN IF NOT EXISTS "batch_size" INTEGER;
    ELSE
        RAISE WARNING 'table dedup_jobs missing; column batch_size not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_jobs') IS NOT NULL THEN
        ALTER TABLE "dedup_jobs" ADD COLUMN IF NOT EXISTS "job_id" TEXT;
    ELSE
        RAISE WARNING 'table dedup_jobs missing; column job_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('dedup_jobs') IS NOT NULL THEN
        ALTER TABLE "dedup_jobs" ADD COLUMN IF NOT EXISTS "modality" TEXT;
    ELSE
        RAISE WARNING 'table dedup_jobs missing; column modality not added';
    END IF;
END $$;

-- document_analyses
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "anomaly_flags" JSONB;
    ELSE
        RAISE WARNING 'table document_analyses missing; column anomaly_flags not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "confidence_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table document_analyses missing; column confidence_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "document_type" TEXT;
    ELSE
        RAISE WARNING 'table document_analyses missing; column document_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "extracted_data" JSONB;
    ELSE
        RAISE WARNING 'table document_analyses missing; column extracted_data not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "file_url" TEXT;
    ELSE
        RAISE WARNING 'table document_analyses missing; column file_url not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "processing_time_ms" INTEGER;
    ELSE
        RAISE WARNING 'table document_analyses missing; column processing_time_ms not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table document_analyses missing; column status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('document_analyses') IS NOT NULL THEN
        ALTER TABLE "document_analyses" ADD COLUMN IF NOT EXISTS "validation_status" TEXT;
    ELSE
        RAISE WARNING 'table document_analyses missing; column validation_status not added';
    END IF;
END $$;

-- election_lifecycle
DO $$
BEGIN
    IF to_regclass('election_lifecycle') IS NOT NULL THEN
        ALTER TABLE "election_lifecycle" ADD COLUMN IF NOT EXISTS "from_state" TEXT;
    ELSE
        RAISE WARNING 'table election_lifecycle missing; column from_state not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_lifecycle') IS NOT NULL THEN
        ALTER TABLE "election_lifecycle" ADD COLUMN IF NOT EXISTS "reason" TEXT;
    ELSE
        RAISE WARNING 'table election_lifecycle missing; column reason not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_lifecycle') IS NOT NULL THEN
        ALTER TABLE "election_lifecycle" ADD COLUMN IF NOT EXISTS "started_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table election_lifecycle missing; column started_at not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_lifecycle') IS NOT NULL THEN
        ALTER TABLE "election_lifecycle" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table election_lifecycle missing; column status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_lifecycle') IS NOT NULL THEN
        ALTER TABLE "election_lifecycle" ADD COLUMN IF NOT EXISTS "to_state" TEXT;
    ELSE
        RAISE WARNING 'table election_lifecycle missing; column to_state not added';
    END IF;
END $$;

-- election_materials
DO $$
BEGIN
    IF to_regclass('election_materials') IS NOT NULL THEN
        ALTER TABLE "election_materials" ADD COLUMN IF NOT EXISTS "category" TEXT;
    ELSE
        RAISE WARNING 'table election_materials missing; column category not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_materials') IS NOT NULL THEN
        ALTER TABLE "election_materials" ADD COLUMN IF NOT EXISTS "name" TEXT;
    ELSE
        RAISE WARNING 'table election_materials missing; column name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_materials') IS NOT NULL THEN
        ALTER TABLE "election_materials" ADD COLUMN IF NOT EXISTS "quantity_allocated" INTEGER;
    ELSE
        RAISE WARNING 'table election_materials missing; column quantity_allocated not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_materials') IS NOT NULL THEN
        ALTER TABLE "election_materials" ADD COLUMN IF NOT EXISTS "quantity_deployed" INTEGER;
    ELSE
        RAISE WARNING 'table election_materials missing; column quantity_deployed not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_materials') IS NOT NULL THEN
        ALTER TABLE "election_materials" ADD COLUMN IF NOT EXISTS "quantity_returned" INTEGER;
    ELSE
        RAISE WARNING 'table election_materials missing; column quantity_returned not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_materials') IS NOT NULL THEN
        ALTER TABLE "election_materials" ADD COLUMN IF NOT EXISTS "tracking_code" TEXT;
    ELSE
        RAISE WARNING 'table election_materials missing; column tracking_code not added';
    END IF;
END $$;

-- election_staff_assignments
DO $$
BEGIN
    IF to_regclass('election_staff_assignments') IS NOT NULL THEN
        ALTER TABLE "election_staff_assignments" ADD COLUMN IF NOT EXISTS "polling_unit_code" TEXT;
    ELSE
        RAISE WARNING 'table election_staff_assignments missing; column polling_unit_code not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_staff_assignments') IS NOT NULL THEN
        ALTER TABLE "election_staff_assignments" ADD COLUMN IF NOT EXISTS "state_code" TEXT;
    ELSE
        RAISE WARNING 'table election_staff_assignments missing; column state_code not added';
    END IF;
END $$;

-- election_state_log
DO $$
BEGIN
    IF to_regclass('election_state_log') IS NOT NULL THEN
        ALTER TABLE "election_state_log" ADD COLUMN IF NOT EXISTS "changed_by" INTEGER;
    ELSE
        RAISE WARNING 'table election_state_log missing; column changed_by not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('election_state_log') IS NOT NULL THEN
        ALTER TABLE "election_state_log" ADD COLUMN IF NOT EXISTS "reason" TEXT;
    ELSE
        RAISE WARNING 'table election_state_log missing; column reason not added';
    END IF;
END $$;

-- elections
DO $$
BEGIN
    IF to_regclass('elections') IS NOT NULL THEN
        ALTER TABLE "elections" ADD COLUMN IF NOT EXISTS "state_code" TEXT;
    ELSE
        RAISE WARNING 'table elections missing; column state_code not added';
    END IF;
END $$;

-- ems_workflow_phases
DO $$
BEGIN
    IF to_regclass('ems_workflow_phases') IS NOT NULL THEN
        ALTER TABLE "ems_workflow_phases" ADD COLUMN IF NOT EXISTS "assigned_to" TEXT;
    ELSE
        RAISE WARNING 'table ems_workflow_phases missing; column assigned_to not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ems_workflow_phases') IS NOT NULL THEN
        ALTER TABLE "ems_workflow_phases" ADD COLUMN IF NOT EXISTS "phase_name" TEXT;
    ELSE
        RAISE WARNING 'table ems_workflow_phases missing; column phase_name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ems_workflow_phases') IS NOT NULL THEN
        ALTER TABLE "ems_workflow_phases" ADD COLUMN IF NOT EXISTS "sequence_order" INTEGER;
    ELSE
        RAISE WARNING 'table ems_workflow_phases missing; column sequence_order not added';
    END IF;
END $$;

-- ems_workflows
DO $$
BEGIN
    IF to_regclass('ems_workflows') IS NOT NULL THEN
        ALTER TABLE "ems_workflows" ADD COLUMN IF NOT EXISTS "created_by" INTEGER;
    ELSE
        RAISE WARNING 'table ems_workflows missing; column created_by not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ems_workflows') IS NOT NULL THEN
        ALTER TABLE "ems_workflows" ADD COLUMN IF NOT EXISTS "name" TEXT;
    ELSE
        RAISE WARNING 'table ems_workflows missing; column name not added';
    END IF;
END $$;

-- escalation_log
DO $$
BEGIN
    IF to_regclass('escalation_log') IS NOT NULL THEN
        ALTER TABLE "escalation_log" ADD COLUMN IF NOT EXISTS "resolved" BOOLEAN;
    ELSE
        RAISE WARNING 'table escalation_log missing; column resolved not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('escalation_log') IS NOT NULL THEN
        ALTER TABLE "escalation_log" ADD COLUMN IF NOT EXISTS "rule_id" INTEGER;
    ELSE
        RAISE WARNING 'table escalation_log missing; column rule_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('escalation_log') IS NOT NULL THEN
        ALTER TABLE "escalation_log" ADD COLUMN IF NOT EXISTS "triggered_by" TEXT;
    ELSE
        RAISE WARNING 'table escalation_log missing; column triggered_by not added';
    END IF;
END $$;

-- escalation_rules
DO $$
BEGIN
    IF to_regclass('escalation_rules') IS NOT NULL THEN
        ALTER TABLE "escalation_rules" ADD COLUMN IF NOT EXISTS "action_type" TEXT;
    ELSE
        RAISE WARNING 'table escalation_rules missing; column action_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('escalation_rules') IS NOT NULL THEN
        ALTER TABLE "escalation_rules" ADD COLUMN IF NOT EXISTS "condition_expr" TEXT;
    ELSE
        RAISE WARNING 'table escalation_rules missing; column condition_expr not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('escalation_rules') IS NOT NULL THEN
        ALTER TABLE "escalation_rules" ADD COLUMN IF NOT EXISTS "cooldown_minutes" INTEGER;
    ELSE
        RAISE WARNING 'table escalation_rules missing; column cooldown_minutes not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('escalation_rules') IS NOT NULL THEN
        ALTER TABLE "escalation_rules" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;
    ELSE
        RAISE WARNING 'table escalation_rules missing; column is_active not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('escalation_rules') IS NOT NULL THEN
        ALTER TABLE "escalation_rules" ADD COLUMN IF NOT EXISTS "severity" TEXT;
    ELSE
        RAISE WARNING 'table escalation_rules missing; column severity not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='escalation_rules' AND column_name='action') THEN
        ALTER TABLE "escalation_rules" ALTER COLUMN "action" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='escalation_rules' AND column_name='condition') THEN
        ALTER TABLE "escalation_rules" ALTER COLUMN "condition" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='escalation_rules' AND column_name='level') THEN
        ALTER TABLE "escalation_rules" ALTER COLUMN "level" DROP NOT NULL;
    END IF;
END $$;

-- export_audit_log
DO $$
BEGIN
    IF to_regclass('export_audit_log') IS NOT NULL THEN
        ALTER TABLE "export_audit_log" ADD COLUMN IF NOT EXISTS "record_count" INTEGER;
    ELSE
        RAISE WARNING 'table export_audit_log missing; column record_count not added';
    END IF;
END $$;

-- fabric_blocks
DO $$
BEGIN
    IF to_regclass('fabric_blocks') IS NOT NULL THEN
        ALTER TABLE "fabric_blocks" ADD COLUMN IF NOT EXISTS "channel" TEXT;
    ELSE
        RAISE WARNING 'table fabric_blocks missing; column channel not added';
    END IF;
END $$;

-- fabric_transactions
DO $$
BEGIN
    IF to_regclass('fabric_transactions') IS NOT NULL THEN
        ALTER TABLE "fabric_transactions" ADD COLUMN IF NOT EXISTS "chaincode" TEXT;
    ELSE
        RAISE WARNING 'table fabric_transactions missing; column chaincode not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('fabric_transactions') IS NOT NULL THEN
        ALTER TABLE "fabric_transactions" ADD COLUMN IF NOT EXISTS "channel" TEXT;
    ELSE
        RAISE WARNING 'table fabric_transactions missing; column channel not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('fabric_transactions') IS NOT NULL THEN
        ALTER TABLE "fabric_transactions" ADD COLUMN IF NOT EXISTS "data_hash" TEXT;
    ELSE
        RAISE WARNING 'table fabric_transactions missing; column data_hash not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('fabric_transactions') IS NOT NULL THEN
        ALTER TABLE "fabric_transactions" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table fabric_transactions missing; column status not added';
    END IF;
END $$;

-- gotv_cpi_history
DO $$
BEGIN
    IF to_regclass('gotv_cpi_history') IS NOT NULL THEN
        ALTER TABLE "gotv_cpi_history" ADD COLUMN IF NOT EXISTS "endorsements" TEXT;
    ELSE
        RAISE WARNING 'table gotv_cpi_history missing; column endorsements not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_cpi_history') IS NOT NULL THEN
        ALTER TABLE "gotv_cpi_history" ADD COLUMN IF NOT EXISTS "favourability" TEXT;
    ELSE
        RAISE WARNING 'table gotv_cpi_history missing; column favourability not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_cpi_history') IS NOT NULL THEN
        ALTER TABLE "gotv_cpi_history" ADD COLUMN IF NOT EXISTS "sentiment" TEXT;
    ELSE
        RAISE WARNING 'table gotv_cpi_history missing; column sentiment not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_cpi_history') IS NOT NULL THEN
        ALTER TABLE "gotv_cpi_history" ADD COLUMN IF NOT EXISTS "voting_intention" TEXT;
    ELSE
        RAISE WARNING 'table gotv_cpi_history missing; column voting_intention not added';
    END IF;
END $$;

-- gotv_field_reports
DO $$
BEGIN
    IF to_regclass('gotv_field_reports') IS NOT NULL THEN
        ALTER TABLE "gotv_field_reports" ADD COLUMN IF NOT EXISTS "lga_code" TEXT;
    ELSE
        RAISE WARNING 'table gotv_field_reports missing; column lga_code not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_field_reports') IS NOT NULL THEN
        ALTER TABLE "gotv_field_reports" ADD COLUMN IF NOT EXISTS "media_url" TEXT;
    ELSE
        RAISE WARNING 'table gotv_field_reports missing; column media_url not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_field_reports') IS NOT NULL THEN
        ALTER TABLE "gotv_field_reports" ADD COLUMN IF NOT EXISTS "report_type" TEXT;
    ELSE
        RAISE WARNING 'table gotv_field_reports missing; column report_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_field_reports') IS NOT NULL THEN
        ALTER TABLE "gotv_field_reports" ADD COLUMN IF NOT EXISTS "state_code" TEXT;
    ELSE
        RAISE WARNING 'table gotv_field_reports missing; column state_code not added';
    END IF;
END $$;

-- gotv_ride_requests
DO $$
BEGIN
    IF to_regclass('gotv_ride_requests') IS NOT NULL THEN
        ALTER TABLE "gotv_ride_requests" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table gotv_ride_requests missing; column created_at not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('gotv_ride_requests') IS NOT NULL THEN
        ALTER TABLE "gotv_ride_requests" ADD COLUMN IF NOT EXISTS "notes" TEXT;
    ELSE
        RAISE WARNING 'table gotv_ride_requests missing; column notes not added';
    END IF;
END $$;

-- gotv_volunteers
DO $$
BEGIN
    IF to_regclass('gotv_volunteers') IS NOT NULL THEN
        ALTER TABLE "gotv_volunteers" ADD COLUMN IF NOT EXISTS "vetting_status" BOOLEAN;
    ELSE
        RAISE WARNING 'table gotv_volunteers missing; column vetting_status not added';
    END IF;
END $$;

-- grievances
DO $$
BEGIN
    IF to_regclass('grievances') IS NOT NULL THEN
        ALTER TABLE "grievances" ADD COLUMN IF NOT EXISTS "category" TEXT;
    ELSE
        RAISE WARNING 'table grievances missing; column category not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('grievances') IS NOT NULL THEN
        ALTER TABLE "grievances" ADD COLUMN IF NOT EXISTS "election_id" INTEGER;
    ELSE
        RAISE WARNING 'table grievances missing; column election_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('grievances') IS NOT NULL THEN
        ALTER TABLE "grievances" ADD COLUMN IF NOT EXISTS "filed_by" INTEGER;
    ELSE
        RAISE WARNING 'table grievances missing; column filed_by not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('grievances') IS NOT NULL THEN
        ALTER TABLE "grievances" ADD COLUMN IF NOT EXISTS "polling_unit_code" TEXT;
    ELSE
        RAISE WARNING 'table grievances missing; column polling_unit_code not added';
    END IF;
END $$;

-- incidents
DO $$
BEGIN
    IF to_regclass('incidents') IS NOT NULL THEN
        ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table incidents missing; column latitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('incidents') IS NOT NULL THEN
        ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table incidents missing; column longitude not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('incidents') IS NOT NULL THEN
        ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "title" TEXT;
    ELSE
        RAISE WARNING 'table incidents missing; column title not added';
    END IF;
END $$;

-- ingestion_jobs
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "job_id" TEXT;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column job_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "output_path" TEXT;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column output_path not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "records_failed" INTEGER;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column records_failed not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "records_processed" INTEGER;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column records_processed not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "records_total" INTEGER;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column records_total not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "source" TEXT;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column source not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "source_type" TEXT;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column source_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ingestion_jobs') IS NOT NULL THEN
        ALTER TABLE "ingestion_jobs" ADD COLUMN IF NOT EXISTS "tier" TEXT;
    ELSE
        RAISE WARNING 'table ingestion_jobs missing; column tier not added';
    END IF;
END $$;

-- kyb_verifications
DO $$
BEGIN
    IF to_regclass('kyb_verifications') IS NOT NULL THEN
        ALTER TABLE "kyb_verifications" ADD COLUMN IF NOT EXISTS "rc_number" INTEGER;
    ELSE
        RAISE WARNING 'table kyb_verifications missing; column rc_number not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('kyb_verifications') IS NOT NULL THEN
        ALTER TABLE "kyb_verifications" ADD COLUMN IF NOT EXISTS "tin" TEXT;
    ELSE
        RAISE WARNING 'table kyb_verifications missing; column tin not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('kyb_verifications') IS NOT NULL THEN
        ALTER TABLE "kyb_verifications" ADD COLUMN IF NOT EXISTS "verified_by" INTEGER;
    ELSE
        RAISE WARNING 'table kyb_verifications missing; column verified_by not added';
    END IF;
END $$;

-- kyc_verifications
DO $$
BEGIN
    IF to_regclass('kyc_verifications') IS NOT NULL THEN
        ALTER TABLE "kyc_verifications" ADD COLUMN IF NOT EXISTS "document_number" INTEGER;
    ELSE
        RAISE WARNING 'table kyc_verifications missing; column document_number not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('kyc_verifications') IS NOT NULL THEN
        ALTER TABLE "kyc_verifications" ADD COLUMN IF NOT EXISTS "document_type" TEXT;
    ELSE
        RAISE WARNING 'table kyc_verifications missing; column document_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('kyc_verifications') IS NOT NULL THEN
        ALTER TABLE "kyc_verifications" ADD COLUMN IF NOT EXISTS "expiry_date" TEXT;
    ELSE
        RAISE WARNING 'table kyc_verifications missing; column expiry_date not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('kyc_verifications') IS NOT NULL THEN
        ALTER TABLE "kyc_verifications" ADD COLUMN IF NOT EXISTS "verification_type" TEXT;
    ELSE
        RAISE WARNING 'table kyc_verifications missing; column verification_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('kyc_verifications') IS NOT NULL THEN
        ALTER TABLE "kyc_verifications" ADD COLUMN IF NOT EXISTS "verified_by" INTEGER;
    ELSE
        RAISE WARNING 'table kyc_verifications missing; column verified_by not added';
    END IF;
END $$;

-- landmarks
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='landmarks' AND column_name='event_type') THEN
        ALTER TABLE "landmarks" ALTER COLUMN "event_type" DROP NOT NULL;
    END IF;
END $$;

-- liveness_checks
DO $$
BEGIN
    IF to_regclass('liveness_checks') IS NOT NULL THEN
        ALTER TABLE "liveness_checks" ADD COLUMN IF NOT EXISTS "attempt_number" INTEGER;
    ELSE
        RAISE WARNING 'table liveness_checks missing; column attempt_number not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('liveness_checks') IS NOT NULL THEN
        ALTER TABLE "liveness_checks" ADD COLUMN IF NOT EXISTS "challenge_type" TEXT;
    ELSE
        RAISE WARNING 'table liveness_checks missing; column challenge_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('liveness_checks') IS NOT NULL THEN
        ALTER TABLE "liveness_checks" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
    ELSE
        RAISE WARNING 'table liveness_checks missing; column device_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('liveness_checks') IS NOT NULL THEN
        ALTER TABLE "liveness_checks" ADD COLUMN IF NOT EXISTS "profile_id" INTEGER;
    ELSE
        RAISE WARNING 'table liveness_checks missing; column profile_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('liveness_checks') IS NOT NULL THEN
        ALTER TABLE "liveness_checks" ADD COLUMN IF NOT EXISTS "result" TEXT;
    ELSE
        RAISE WARNING 'table liveness_checks missing; column result not added';
    END IF;
END $$;

-- mfa_settings
DO $$
BEGIN
    IF to_regclass('mfa_settings') IS NOT NULL THEN
        ALTER TABLE "mfa_settings" ADD COLUMN IF NOT EXISTS "backup_codes" TEXT;
    ELSE
        RAISE WARNING 'table mfa_settings missing; column backup_codes not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mfa_settings') IS NOT NULL THEN
        ALTER TABLE "mfa_settings" ADD COLUMN IF NOT EXISTS "is_enabled" BOOLEAN;
    ELSE
        RAISE WARNING 'table mfa_settings missing; column is_enabled not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mfa_settings') IS NOT NULL THEN
        ALTER TABLE "mfa_settings" ADD COLUMN IF NOT EXISTS "method" TEXT;
    ELSE
        RAISE WARNING 'table mfa_settings missing; column method not added';
    END IF;
END $$;

-- model_metrics
DO $$
BEGIN
    IF to_regclass('model_metrics') IS NOT NULL THEN
        ALTER TABLE "model_metrics" ADD COLUMN IF NOT EXISTS "f1_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table model_metrics missing; column f1_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('model_metrics') IS NOT NULL THEN
        ALTER TABLE "model_metrics" ADD COLUMN IF NOT EXISTS "precision_score" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table model_metrics missing; column precision_score not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('model_metrics') IS NOT NULL THEN
        ALTER TABLE "model_metrics" ADD COLUMN IF NOT EXISTS "recall" TEXT;
    ELSE
        RAISE WARNING 'table model_metrics missing; column recall not added';
    END IF;
END $$;

-- mw_events
DO $$
BEGIN
    IF to_regclass('mw_events') IS NOT NULL THEN
        ALTER TABLE "mw_events" ADD COLUMN IF NOT EXISTS "details" JSONB;
    ELSE
        RAISE WARNING 'table mw_events missing; column details not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mw_events') IS NOT NULL THEN
        ALTER TABLE "mw_events" ADD COLUMN IF NOT EXISTS "event_type" TEXT;
    ELSE
        RAISE WARNING 'table mw_events missing; column event_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mw_events') IS NOT NULL THEN
        ALTER TABLE "mw_events" ADD COLUMN IF NOT EXISTS "message" TEXT;
    ELSE
        RAISE WARNING 'table mw_events missing; column message not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mw_events') IS NOT NULL THEN
        ALTER TABLE "mw_events" ADD COLUMN IF NOT EXISTS "middleware" TEXT;
    ELSE
        RAISE WARNING 'table mw_events missing; column middleware not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mw_events') IS NOT NULL THEN
        ALTER TABLE "mw_events" ADD COLUMN IF NOT EXISTS "severity" TEXT;
    ELSE
        RAISE WARNING 'table mw_events missing; column severity not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mw_events' AND column_name='topic') THEN
        ALTER TABLE "mw_events" ALTER COLUMN "topic" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mw_events' AND column_name='value') THEN
        ALTER TABLE "mw_events" ALTER COLUMN "value" DROP NOT NULL;
    END IF;
END $$;

-- mw_state
DO $$
BEGIN
    IF to_regclass('mw_state') IS NOT NULL THEN
        ALTER TABLE "mw_state" ADD COLUMN IF NOT EXISTS "last_check" TEXT;
    ELSE
        RAISE WARNING 'table mw_state missing; column last_check not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mw_state') IS NOT NULL THEN
        ALTER TABLE "mw_state" ADD COLUMN IF NOT EXISTS "name" TEXT;
    ELSE
        RAISE WARNING 'table mw_state missing; column name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('mw_state') IS NOT NULL THEN
        ALTER TABLE "mw_state" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table mw_state missing; column status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mw_state' AND column_name='key') THEN
        ALTER TABLE "mw_state" ALTER COLUMN "key" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mw_state' AND column_name='store_name') THEN
        ALTER TABLE "mw_state" ALTER COLUMN "store_name" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mw_state' AND column_name='value') THEN
        ALTER TABLE "mw_state" ALTER COLUMN "value" DROP NOT NULL;
    END IF;
END $$;

-- observer_alert_rules
DO $$
BEGIN
    IF to_regclass('observer_alert_rules') IS NOT NULL THEN
        ALTER TABLE "observer_alert_rules" ADD COLUMN IF NOT EXISTS "action" TEXT;
    ELSE
        RAISE WARNING 'table observer_alert_rules missing; column action not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('observer_alert_rules') IS NOT NULL THEN
        ALTER TABLE "observer_alert_rules" ADD COLUMN IF NOT EXISTS "condition_expr" TEXT;
    ELSE
        RAISE WARNING 'table observer_alert_rules missing; column condition_expr not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('observer_alert_rules') IS NOT NULL THEN
        ALTER TABLE "observer_alert_rules" ADD COLUMN IF NOT EXISTS "cooldown_minutes" INTEGER;
    ELSE
        RAISE WARNING 'table observer_alert_rules missing; column cooldown_minutes not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('observer_alert_rules') IS NOT NULL THEN
        ALTER TABLE "observer_alert_rules" ADD COLUMN IF NOT EXISTS "name" TEXT;
    ELSE
        RAISE WARNING 'table observer_alert_rules missing; column name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('observer_alert_rules') IS NOT NULL THEN
        ALTER TABLE "observer_alert_rules" ADD COLUMN IF NOT EXISTS "severity" TEXT;
    ELSE
        RAISE WARNING 'table observer_alert_rules missing; column severity not added';
    END IF;
END $$;

-- official_tracking
DO $$
BEGIN
    ALTER TABLE "official_tracking" ADD COLUMN IF NOT EXISTS "geom" GEOGRAPHY(POINT,4326);
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'skipping official_tracking.geom: %', SQLERRM;
END $$;

-- offline_sync_queue
DO $$
BEGIN
    IF to_regclass('offline_sync_queue') IS NOT NULL THEN
        ALTER TABLE "offline_sync_queue" ADD COLUMN IF NOT EXISTS "data_type" TEXT;
    ELSE
        RAISE WARNING 'table offline_sync_queue missing; column data_type not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('offline_sync_queue') IS NOT NULL THEN
        ALTER TABLE "offline_sync_queue" ADD COLUMN IF NOT EXISTS "priority" TEXT;
    ELSE
        RAISE WARNING 'table offline_sync_queue missing; column priority not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('offline_sync_queue') IS NOT NULL THEN
        ALTER TABLE "offline_sync_queue" ADD COLUMN IF NOT EXISTS "retry_count" INTEGER;
    ELSE
        RAISE WARNING 'table offline_sync_queue missing; column retry_count not added';
    END IF;
END $$;

-- polling_unit_locations
DO $$
BEGIN
    ALTER TABLE "polling_unit_locations" ADD COLUMN IF NOT EXISTS "geom" GEOGRAPHY(POINT,4326);
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'skipping polling_unit_locations.geom: %', SQLERRM;
END $$;

-- portal_connections
DO $$
BEGIN
    IF to_regclass('portal_connections') IS NOT NULL THEN
        ALTER TABLE "portal_connections" ADD COLUMN IF NOT EXISTS "endpoint_url" TEXT;
    ELSE
        RAISE WARNING 'table portal_connections missing; column endpoint_url not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('portal_connections') IS NOT NULL THEN
        ALTER TABLE "portal_connections" ADD COLUMN IF NOT EXISTS "last_sync" TEXT;
    ELSE
        RAISE WARNING 'table portal_connections missing; column last_sync not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('portal_connections') IS NOT NULL THEN
        ALTER TABLE "portal_connections" ADD COLUMN IF NOT EXISTS "name" TEXT;
    ELSE
        RAISE WARNING 'table portal_connections missing; column name not added';
    END IF;
END $$;

-- portal_webhooks
DO $$
BEGIN
    IF to_regclass('portal_webhooks') IS NOT NULL THEN
        ALTER TABLE "portal_webhooks" ADD COLUMN IF NOT EXISTS "endpoint_url" TEXT;
    ELSE
        RAISE WARNING 'table portal_webhooks missing; column endpoint_url not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('portal_webhooks') IS NOT NULL THEN
        ALTER TABLE "portal_webhooks" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;
    ELSE
        RAISE WARNING 'table portal_webhooks missing; column is_active not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('portal_webhooks') IS NOT NULL THEN
        ALTER TABLE "portal_webhooks" ADD COLUMN IF NOT EXISTS "secret_hash" TEXT;
    ELSE
        RAISE WARNING 'table portal_webhooks missing; column secret_hash not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='portal_webhooks' AND column_name='payload') THEN
        ALTER TABLE "portal_webhooks" ALTER COLUMN "payload" DROP NOT NULL;
    END IF;
END $$;

-- push_notifications
DO $$
BEGIN
    IF to_regclass('push_notifications') IS NOT NULL THEN
        ALTER TABLE "push_notifications" ADD COLUMN IF NOT EXISTS "channel" TEXT;
    ELSE
        RAISE WARNING 'table push_notifications missing; column channel not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('push_notifications') IS NOT NULL THEN
        ALTER TABLE "push_notifications" ADD COLUMN IF NOT EXISTS "election_id" INTEGER;
    ELSE
        RAISE WARNING 'table push_notifications missing; column election_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('push_notifications') IS NOT NULL THEN
        ALTER TABLE "push_notifications" ADD COLUMN IF NOT EXISTS "priority" TEXT;
    ELSE
        RAISE WARNING 'table push_notifications missing; column priority not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('push_notifications') IS NOT NULL THEN
        ALTER TABLE "push_notifications" ADD COLUMN IF NOT EXISTS "recipients" JSONB;
    ELSE
        RAISE WARNING 'table push_notifications missing; column recipients not added';
    END IF;
END $$;

-- registration_centers
DO $$
BEGIN
    IF to_regclass('registration_centers') IS NOT NULL THEN
        ALTER TABLE "registration_centers" ADD COLUMN IF NOT EXISTS "equipment_status" TEXT;
    ELSE
        RAISE WARNING 'table registration_centers missing; column equipment_status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('registration_centers') IS NOT NULL THEN
        ALTER TABLE "registration_centers" ADD COLUMN IF NOT EXISTS "operating_hours" TEXT;
    ELSE
        RAISE WARNING 'table registration_centers missing; column operating_hours not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('registration_centers') IS NOT NULL THEN
        ALTER TABLE "registration_centers" ADD COLUMN IF NOT EXISTS "supervisor_id" INTEGER;
    ELSE
        RAISE WARNING 'table registration_centers missing; column supervisor_id not added';
    END IF;
END $$;

-- result_signatures
DO $$
BEGIN
    IF to_regclass('result_signatures') IS NOT NULL THEN
        ALTER TABLE "result_signatures" ADD COLUMN IF NOT EXISTS "algorithm" TEXT;
    ELSE
        RAISE WARNING 'table result_signatures missing; column algorithm not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('result_signatures') IS NOT NULL THEN
        ALTER TABLE "result_signatures" ADD COLUMN IF NOT EXISTS "signature_hash" TEXT;
    ELSE
        RAISE WARNING 'table result_signatures missing; column signature_hash not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('result_signatures') IS NOT NULL THEN
        ALTER TABLE "result_signatures" ADD COLUMN IF NOT EXISTS "signer_id" INTEGER;
    ELSE
        RAISE WARNING 'table result_signatures missing; column signer_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('result_signatures') IS NOT NULL THEN
        ALTER TABLE "result_signatures" ADD COLUMN IF NOT EXISTS "signer_role" TEXT;
    ELSE
        RAISE WARNING 'table result_signatures missing; column signer_role not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('result_signatures') IS NOT NULL THEN
        ALTER TABLE "result_signatures" ADD COLUMN IF NOT EXISTS "verification_status" TEXT;
    ELSE
        RAISE WARNING 'table result_signatures missing; column verification_status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='result_signatures' AND column_name='officer_pubkey') THEN
        ALTER TABLE "result_signatures" ALTER COLUMN "officer_pubkey" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='result_signatures' AND column_name='result_hash') THEN
        ALTER TABLE "result_signatures" ALTER COLUMN "result_hash" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='result_signatures' AND column_name='signature') THEN
        ALTER TABLE "result_signatures" ALTER COLUMN "signature" DROP NOT NULL;
    END IF;
END $$;

-- results
DO $$
BEGIN
    IF to_regclass('results') IS NOT NULL THEN
        ALTER TABLE "results" ADD COLUMN IF NOT EXISTS "lga" TEXT;
    ELSE
        RAISE WARNING 'table results missing; column lga not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('results') IS NOT NULL THEN
        ALTER TABLE "results" ADD COLUMN IF NOT EXISTS "state" TEXT;
    ELSE
        RAISE WARNING 'table results missing; column state not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('results') IS NOT NULL THEN
        ALTER TABLE "results" ADD COLUMN IF NOT EXISTS "submitted_by" INTEGER;
    ELSE
        RAISE WARNING 'table results missing; column submitted_by not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('results') IS NOT NULL THEN
        ALTER TABLE "results" ADD COLUMN IF NOT EXISTS "total_votes" INTEGER;
    ELSE
        RAISE WARNING 'table results missing; column total_votes not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('results') IS NOT NULL THEN
        ALTER TABLE "results" ADD COLUMN IF NOT EXISTS "ward" TEXT;
    ELSE
        RAISE WARNING 'table results missing; column ward not added';
    END IF;
END $$;

-- security_audit_events
DO $$
BEGIN
    IF to_regclass('security_audit_events') IS NOT NULL THEN
        ALTER TABLE "security_audit_events" ADD COLUMN IF NOT EXISTS "user_agent" TEXT;
    ELSE
        RAISE WARNING 'table security_audit_events missing; column user_agent not added';
    END IF;
END $$;

-- sms_verifications
DO $$
BEGIN
    IF to_regclass('sms_verifications') IS NOT NULL THEN
        ALTER TABLE "sms_verifications" ADD COLUMN IF NOT EXISTS "attempts" TEXT;
    ELSE
        RAISE WARNING 'table sms_verifications missing; column attempts not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('sms_verifications') IS NOT NULL THEN
        ALTER TABLE "sms_verifications" ADD COLUMN IF NOT EXISTS "code" TEXT;
    ELSE
        RAISE WARNING 'table sms_verifications missing; column code not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('sms_verifications') IS NOT NULL THEN
        ALTER TABLE "sms_verifications" ADD COLUMN IF NOT EXISTS "purpose" TEXT;
    ELSE
        RAISE WARNING 'table sms_verifications missing; column purpose not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('sms_verifications') IS NOT NULL THEN
        ALTER TABLE "sms_verifications" ADD COLUMN IF NOT EXISTS "verified" BOOLEAN;
    ELSE
        RAISE WARNING 'table sms_verifications missing; column verified not added';
    END IF;
END $$;

-- stablecoin_ledger
DO $$
BEGIN
    IF to_regclass('stablecoin_ledger') IS NOT NULL THEN
        ALTER TABLE "stablecoin_ledger" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table stablecoin_ledger missing; column amount not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('stablecoin_ledger') IS NOT NULL THEN
        ALTER TABLE "stablecoin_ledger" ADD COLUMN IF NOT EXISTS "balance_after" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table stablecoin_ledger missing; column balance_after not added';
    END IF;
END $$;

-- stablecoin_transactions
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='stablecoin_transactions' AND column_name='from_account') THEN
        ALTER TABLE "stablecoin_transactions" ALTER COLUMN "from_account" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='stablecoin_transactions' AND column_name='to_account') THEN
        ALTER TABLE "stablecoin_transactions" ALTER COLUMN "to_account" DROP NOT NULL;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='stablecoin_transactions' AND column_name='transaction_id') THEN
        ALTER TABLE "stablecoin_transactions" ALTER COLUMN "transaction_id" DROP NOT NULL;
    END IF;
END $$;

-- stablecoin_wallets
DO $$
BEGIN
    IF to_regclass('stablecoin_wallets') IS NOT NULL THEN
        ALTER TABLE "stablecoin_wallets" ADD COLUMN IF NOT EXISTS "balance" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table stablecoin_wallets missing; column balance not added';
    END IF;
END $$;

-- stakeholders
DO $$
BEGIN
    IF to_regclass('stakeholders') IS NOT NULL THEN
        ALTER TABLE "stakeholders" ADD COLUMN IF NOT EXISTS "contact_person" TEXT;
    ELSE
        RAISE WARNING 'table stakeholders missing; column contact_person not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('stakeholders') IS NOT NULL THEN
        ALTER TABLE "stakeholders" ADD COLUMN IF NOT EXISTS "org_name" TEXT;
    ELSE
        RAISE WARNING 'table stakeholders missing; column org_name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('stakeholders') IS NOT NULL THEN
        ALTER TABLE "stakeholders" ADD COLUMN IF NOT EXISTS "state_code" TEXT;
    ELSE
        RAISE WARNING 'table stakeholders missing; column state_code not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('stakeholders') IS NOT NULL THEN
        ALTER TABLE "stakeholders" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table stakeholders missing; column status not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('stakeholders') IS NOT NULL THEN
        ALTER TABLE "stakeholders" ADD COLUMN IF NOT EXISTS "type" TEXT;
    ELSE
        RAISE WARNING 'table stakeholders missing; column type not added';
    END IF;
END $$;

-- tb_accounts
DO $$
BEGIN
    IF to_regclass('tb_accounts') IS NOT NULL THEN
        ALTER TABLE "tb_accounts" ADD COLUMN IF NOT EXISTS "account_id" TEXT;
    ELSE
        RAISE WARNING 'table tb_accounts missing; column account_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_accounts') IS NOT NULL THEN
        ALTER TABLE "tb_accounts" ADD COLUMN IF NOT EXISTS "credit_balance" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table tb_accounts missing; column credit_balance not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_accounts') IS NOT NULL THEN
        ALTER TABLE "tb_accounts" ADD COLUMN IF NOT EXISTS "currency" TEXT;
    ELSE
        RAISE WARNING 'table tb_accounts missing; column currency not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_accounts') IS NOT NULL THEN
        ALTER TABLE "tb_accounts" ADD COLUMN IF NOT EXISTS "debit_balance" DOUBLE PRECISION;
    ELSE
        RAISE WARNING 'table tb_accounts missing; column debit_balance not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_accounts') IS NOT NULL THEN
        ALTER TABLE "tb_accounts" ADD COLUMN IF NOT EXISTS "description" TEXT;
    ELSE
        RAISE WARNING 'table tb_accounts missing; column description not added';
    END IF;
END $$;

-- tb_transfers
DO $$
BEGIN
    IF to_regclass('tb_transfers') IS NOT NULL THEN
        ALTER TABLE "tb_transfers" ADD COLUMN IF NOT EXISTS "credit_account" TEXT;
    ELSE
        RAISE WARNING 'table tb_transfers missing; column credit_account not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_transfers') IS NOT NULL THEN
        ALTER TABLE "tb_transfers" ADD COLUMN IF NOT EXISTS "debit_account" TEXT;
    ELSE
        RAISE WARNING 'table tb_transfers missing; column debit_account not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_transfers') IS NOT NULL THEN
        ALTER TABLE "tb_transfers" ADD COLUMN IF NOT EXISTS "description" TEXT;
    ELSE
        RAISE WARNING 'table tb_transfers missing; column description not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('tb_transfers') IS NOT NULL THEN
        ALTER TABLE "tb_transfers" ADD COLUMN IF NOT EXISTS "transfer_id" TEXT;
    ELSE
        RAISE WARNING 'table tb_transfers missing; column transfer_id not added';
    END IF;
END $$;

-- training_courses
DO $$
BEGIN
    IF to_regclass('training_courses') IS NOT NULL THEN
        ALTER TABLE "training_courses" ADD COLUMN IF NOT EXISTS "duration_hours" INTEGER;
    ELSE
        RAISE WARNING 'table training_courses missing; column duration_hours not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('training_courses') IS NOT NULL THEN
        ALTER TABLE "training_courses" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table training_courses missing; column status not added';
    END IF;
END $$;

-- users
DO $$
BEGIN
    IF to_regclass('users') IS NOT NULL THEN
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" TEXT;
    ELSE
        RAISE WARNING 'table users missing; column email not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('users') IS NOT NULL THEN
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "login_count" INTEGER;
    ELSE
        RAISE WARNING 'table users missing; column login_count not added';
    END IF;
END $$;

-- ussd_sessions
DO $$
BEGIN
    IF to_regclass('ussd_sessions') IS NOT NULL THEN
        ALTER TABLE "ussd_sessions" ADD COLUMN IF NOT EXISTS "last_input" TEXT;
    ELSE
        RAISE WARNING 'table ussd_sessions missing; column last_input not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ussd_sessions') IS NOT NULL THEN
        ALTER TABLE "ussd_sessions" ADD COLUMN IF NOT EXISTS "session_id" TEXT;
    ELSE
        RAISE WARNING 'table ussd_sessions missing; column session_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('ussd_sessions') IS NOT NULL THEN
        ALTER TABLE "ussd_sessions" ADD COLUMN IF NOT EXISTS "state" TEXT;
    ELSE
        RAISE WARNING 'table ussd_sessions missing; column state not added';
    END IF;
END $$;

-- validation_results
DO $$
BEGIN
    IF to_regclass('validation_results') IS NOT NULL THEN
        ALTER TABLE "validation_results" ADD COLUMN IF NOT EXISTS "election_id" INTEGER;
    ELSE
        RAISE WARNING 'table validation_results missing; column election_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('validation_results') IS NOT NULL THEN
        ALTER TABLE "validation_results" ADD COLUMN IF NOT EXISTS "polling_unit_code" TEXT;
    ELSE
        RAISE WARNING 'table validation_results missing; column polling_unit_code not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('validation_results') IS NOT NULL THEN
        ALTER TABLE "validation_results" ADD COLUMN IF NOT EXISTS "result_id" INTEGER;
    ELSE
        RAISE WARNING 'table validation_results missing; column result_id not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('validation_results') IS NOT NULL THEN
        ALTER TABLE "validation_results" ADD COLUMN IF NOT EXISTS "status" TEXT;
    ELSE
        RAISE WARNING 'table validation_results missing; column status not added';
    END IF;
END $$;

-- validation_rules
DO $$
BEGIN
    IF to_regclass('validation_rules') IS NOT NULL THEN
        ALTER TABLE "validation_rules" ADD COLUMN IF NOT EXISTS "auto_flag" BOOLEAN;
    ELSE
        RAISE WARNING 'table validation_rules missing; column auto_flag not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('validation_rules') IS NOT NULL THEN
        ALTER TABLE "validation_rules" ADD COLUMN IF NOT EXISTS "category" TEXT;
    ELSE
        RAISE WARNING 'table validation_rules missing; column category not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('validation_rules') IS NOT NULL THEN
        ALTER TABLE "validation_rules" ADD COLUMN IF NOT EXISTS "name" TEXT;
    ELSE
        RAISE WARNING 'table validation_rules missing; column name not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('validation_rules') IS NOT NULL THEN
        ALTER TABLE "validation_rules" ADD COLUMN IF NOT EXISTS "query_template" TEXT;
    ELSE
        RAISE WARNING 'table validation_rules missing; column query_template not added';
    END IF;
END $$;

-- voters
DO $$
BEGIN
    IF to_regclass('voters') IS NOT NULL THEN
        ALTER TABLE "voters" ADD COLUMN IF NOT EXISTS "biometric_captured" BOOLEAN;
    ELSE
        RAISE WARNING 'table voters missing; column biometric_captured not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('voters') IS NOT NULL THEN
        ALTER TABLE "voters" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table voters missing; column created_at not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('voters') IS NOT NULL THEN
        ALTER TABLE "voters" ADD COLUMN IF NOT EXISTS "photo_url" TEXT;
    ELSE
        RAISE WARNING 'table voters missing; column photo_url not added';
    END IF;
END $$;
DO $$
BEGIN
    IF to_regclass('voters') IS NOT NULL THEN
        ALTER TABLE "voters" ADD COLUMN IF NOT EXISTS "registration_status" TEXT;
    ELSE
        RAISE WARNING 'table voters missing; column registration_status not added';
    END IF;
END $$;

-- waf_blocklist
DO $$
BEGIN
    IF to_regclass('waf_blocklist') IS NOT NULL THEN
        ALTER TABLE "waf_blocklist" ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMP;
    ELSE
        RAISE WARNING 'table waf_blocklist missing; column expires_at not added';
    END IF;
END $$;

-- Embedded OpenSearch document store (mw_opensearch)
CREATE TABLE IF NOT EXISTS search_documents (
    id BIGSERIAL PRIMARY KEY,
    index_name TEXT NOT NULL,
    doc_id TEXT NOT NULL,
    content JSONB,
    text_content TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (index_name, doc_id)
);
