apiVersion: v1
kind: Service
metadata:
  name: ai-anomaly-detection
  namespace: inec
spec:
  clusterIP: 10.96.27.163
  clusterIPs:
  - 10.96.27.163
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app.kubernetes.io/name: ai-anomaly-detection
  sessionAffinity: None
  type: ClusterIP