apiVersion: v1
kind: Service
metadata:
  name: biometric-python
  namespace: inec
spec:
  clusterIP: 10.96.193.121
  clusterIPs:
  - 10.96.193.121
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app.kubernetes.io/name: biometric-python
  sessionAffinity: None
  type: ClusterIP