apiVersion: v1
kind: Service
metadata:
  name: campaign-planning
  namespace: inec
spec:
  clusterIP: 10.96.188.94
  clusterIPs:
  - 10.96.188.94
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8206
    protocol: TCP
    targetPort: 8206
  selector:
    app.kubernetes.io/name: campaign-planning
  sessionAffinity: None
  type: ClusterIP