apiVersion: v1
kind: Service
metadata:
  name: federated-fraud-detection
  namespace: inec
spec:
  clusterIP: 10.96.116.236
  clusterIPs:
  - 10.96.116.236
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8202
    protocol: TCP
    targetPort: 8202
  selector:
    app.kubernetes.io/name: federated-fraud-detection
  sessionAffinity: None
  type: ClusterIP