apiVersion: apps/v1
kind: Deployment
metadata:
  name: homomorphic-tally
  namespace: inec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: homomorphic-tally
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homomorphic-tally
    spec:
      automountServiceAccountToken: true
      containers:
      - image: registry.digitalocean.com/talentgraph-auth/homomorphic-tally:archive-20260722-014109 # {"$imagepolicy": "flux-system:inec-homomorphic-tally"}
        imagePullPolicy: IfNotPresent
        name: homomorphic-tally
        ports:
        - containerPort: 8201
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      imagePullSecrets:
      - name: talentgraph-auth-pull
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30