apiVersion: v1
kind: Service
metadata:
  name: inec-backend
  namespace: inec
spec:
  clusterIP: 10.96.45.182
  clusterIPs:
  - 10.96.45.182
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app.kubernetes.io/name: inec-backend
  sessionAffinity: None
  type: ClusterIP