apiVersion: v1
kind: Service
metadata:
  name: satellite-change-detection
  namespace: inec
spec:
  clusterIP: 10.96.92.108
  clusterIPs:
  - 10.96.92.108
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8204
    protocol: TCP
    targetPort: 8204
  selector:
    app.kubernetes.io/name: satellite-change-detection
  sessionAffinity: None
  type: ClusterIP